#!/usr/bin/env python3
"""Feature 026 goldens: the dense stage's expectations under eight-bit storage.

Principle II says a golden comes from `reference/`, not from the implementation it checks. The
scheme itself lives once, in `dense_format3.py`; the goldens are minted by their own generators
(`gen_004_fixtures.py`, `gen_005_fixtures.py`), which import it. This file is the **checker**:
it recomputes every expectation the dense stage's tests replay from that module, so CI can
prove the committed goldens are the scheme's without torch or a model, and it writes the
scripted oracle's expectations.

It checks, or rewrites in place:

* `reference/fixtures/004/search.json` — every case's expected hits and scores;
* `reference/fixtures/004/mutations.json` — the same, after each scripted mutation;
* `reference/fixtures/005/hybrid.json` — the pipeline's expected dense scores;
* `crates/xtriever-dense/tests/support/v3_oracle.json` — the scripted sequences that were
  minted on format 1 and replayed unchanged through format 2. **Format 3 changes scores by
  design**, so the file is re-minted rather than pretended to be unchanged, and it is renamed to
  say which format it describes. The crate's `mint` test writes the *steps* (and its own
  provisional hits); the committed expectations are the ones this file writes with
  `--write-oracle`, so the golden is generated by `reference/`, as Principle II asks, and the
  crate's `replay` test is checked against it rather than the other way round.

    python3 reference/gen_026_fixtures.py                 # check the 004/005 goldens; exit 1 on a difference
    python3 reference/gen_026_fixtures.py --write         # rewrite the 004/005 goldens
    python3 reference/gen_026_fixtures.py --check-oracle  # check the oracle; exit 1 on a mismatch
    python3 reference/gen_026_fixtures.py --write-oracle  # write the oracle's expectations

CI runs the two check modes on every push (`.github/workflows/ci.yml`, job `test`).
"""

from __future__ import annotations

import argparse
import hashlib
import json
import math
import struct
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FIXTURES = ROOT / "reference/fixtures/004"
PIPELINE = ROOT / "reference/fixtures/005/hybrid.json"
ORACLE_OUT = ROOT / "crates/xtriever-dense/tests/support/v3_oracle.json"
SCHEME = ROOT / "reference/dense_format3.py"

from dense_format3 import Prepared, f32, ranked, score  # noqa: E402  (the scheme, once)


def rescore_search(document: dict) -> int:
    """Recompute `search.json`'s expectations. Returns how many cases changed."""
    changed = 0
    for group in document["sets"]:
        metric = group["metric"]
        rows = {row["id"]: Prepared(row["vector"]) for row in group["rows"]}
        for query in group["queries"]:
            q = Prepared(query["vector"])
            scores = {i: score(metric, q, v) for i, v in rows.items()}
            for case in query["cases"]:
                allowed = None if case["allowed"] is None else set(case["allowed"])
                if case["k"] == 0 or allowed == set():
                    expected = []
                else:
                    expected = [
                        {"id": i, "score": s} for i, s in ranked(scores, allowed)[: case["k"]]
                    ]
                if expected != case["expected"]:
                    changed += 1
                    case["expected"] = expected
    return changed


def rescore_mutations(document: dict) -> int:
    """`mutations.json` is one scripted stream of `add` / `delete` / `commit` / `expect` steps;
    each `expect` names a query and the results the stage must return at that point."""
    metric = document["metric"]
    live: dict[int, list[float]] = {}
    committed: dict[int, list[float]] = {}
    changed = 0
    for step in document["steps"]:
        op = step["op"]
        if op in ("add", "replace"):
            live[step["id"]] = [f32(x) for x in step["vector"]]
        elif op == "delete":
            for doomed in step["ids"]:
                live.pop(doomed, None)
        elif op == "commit":
            committed = dict(live)
        elif op == "reopen":
            # A reopen drops whatever was staged and never committed (step 19's add is gone by
            # step 21's expect, which is why the script has it).
            live = dict(committed)
        elif op != "expect":
            # A step this model does not know would leave it stale while the check still said
            # "0 differences": refuse, so a new op is a change here too.
            raise SystemExit(f"mutations.json: unknown op {op!r} at step {document['steps'].index(step)}")
        if op == "expect":
            q = Prepared(step["query"])
            scores = {i: score(metric, q, Prepared(v)) for i, v in committed.items()}
            results = [
                {"id": i, "score": s} for i, s in ranked(scores, None)[: step["k"]]
            ]
            if results != step["results"]:
                changed += 1
                step["results"] = results
            if len(committed) != step["len"]:
                raise SystemExit(
                    f"mutations.json: len {step['len']} but the model holds {len(committed)}"
                )
    return changed


def resolve_filter(filter_: dict | None, docs: list[dict]) -> set[str] | None:
    """The query's filter as `gen_005_fixtures.py` resolves it: the allowed external ids, or
    `None` for no filter. Restated here because that generator imports numpy and this checker
    must stay standard-library for CI."""
    if filter_ is None:
        return None
    (kind, payload), = filter_.items()
    if kind == "Eq":
        field, value = payload
        (_, val), = value.items()
        return {d["external_id"] for d in docs if d["fields"].get(field, {}).get("Keyword") == val}
    if kind == "In":
        field, values = payload
        vals = {list(v.values())[0] for v in values}
        return {d["external_id"] for d in docs if d["fields"].get(field, {}).get("Keyword") in vals}
    if kind == "Not":
        inner = resolve_filter(payload, docs)
        return {d["external_id"] for d in docs} - inner
    raise ValueError(kind)


def rescore_pipeline(document: dict) -> int:
    """The pipeline fixture's expected dense scores, recomputed under format 3.

    The hybrid fixture carries its own document vectors and a query vector per case, and the
    dense stage there is cosine over unit-length vectors. Every document the query's *filter*
    admits is scored — not just the ids the committed golden lists, which would let a stale
    ranking pass (Copilot, PR A) — and the ranking is cut at the golden's depth. Fusion is
    untouched: reciprocal rank fusion reads ranks, not scores, so the fused expectations move
    only if a rank moves — and the test asserts that too, which is the point of recomputing
    rather than loosening.
    """
    docs = document["documents"]
    rows = {doc["external_id"]: Prepared(doc["vector"]) for doc in docs}
    # The stage breaks ties by ascending *internal* id — ingestion order, the position in `docs`.
    order = {doc["external_id"]: i for i, doc in enumerate(docs)}
    changed = 0
    for query in document["queries"]:
        q = Prepared(query["vector"])
        allowed = resolve_filter(query.get("filter"), docs)
        scores = {i: score("cosine", q, v) for i, v in rows.items() if allowed is None or i in allowed}
        depth = len(query["expected_dense"])
        by_score = sorted(scores.items(), key=lambda pair: (-pair[1], order[pair[0]]))
        recomputed = [{"id": i, "score": s} for i, s in by_score[:depth]]
        if recomputed != query["expected_dense"]:
            changed += 1
            query["expected_dense"] = recomputed
    return changed


def sha256_file(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def refresh_manifest(directory: Path) -> None:
    """Keep a fixture directory's `manifest.json` honest: the files' hashes and the scheme.

    `generator_sha256` names the generator that minted the fixture (Feature 004's or 005's);
    `scheme_sha256` pins `dense_format3.py`, which that generator scores with. Both directories'
    tests assert both hashes, so neither the generator nor the scheme can change without the
    goldens being regenerated.
    """
    path = directory / "manifest.json"
    manifest = json.loads(path.read_text(encoding="utf-8"))
    for name in manifest["files"]:
        manifest["files"][name] = sha256_file(directory / name)
    manifest.pop("rescored_by", None)
    manifest.pop("rescored_by_sha256", None)
    manifest["scheme"] = "reference/dense_format3.py"
    manifest["scheme_sha256"] = sha256_file(SCHEME)
    path.write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(f"  {directory.name}/manifest.json: hashes refreshed, scheme pinned")


def recompute_oracle(oracle: dict, write: bool) -> tuple[int, int]:
    """Recompute every expectation in the scripted oracle from the contract's arithmetic.

    Returns `(checked, mismatches)` against what the file holds; with `write`, the file's
    expectations are replaced by the recomputed ones on the way, so the committed golden is
    this generator's, and the crate's `replay` test is what gets checked against it.
    """
    mismatches = 0
    checked = 0
    for sequence in oracle["sequences"]:
        metric = sequence["metric"]
        live: dict[int, list[float]] = {}
        committed: dict[int, list[float]] = {}
        for step in sequence["steps"]:
            op = step["op"]
            if op in ("add", "replace"):
                live[step["id"]] = [f32(x) for x in step["vector"]]
            elif op == "delete":
                for doomed in step.get("ids", [step.get("id")]):
                    live.pop(doomed, None)
            elif op == "commit":
                committed = dict(live)
            elif op == "reopen":
                live = dict(committed)          # staged changes do not survive a reopen
            elif op != "expect":
                raise SystemExit(f"{ORACLE_OUT.name}: unknown op {op!r} in the {metric} sequence")
            if op == "expect":
                if len(committed) != step["len"]:
                    raise SystemExit(
                        f"{ORACLE_OUT.name}: expected {step['len']} live rows, model holds {len(committed)}"
                    )
                rows = {i: Prepared(v) for i, v in committed.items()}
                for query in step["queries"]:
                    q = Prepared(query["vector"])
                    scores = {i: score(metric, q, v) for i, v in rows.items()}
                    allowed = None if query.get("allowed") is None else set(query["allowed"])
                    hits = [
                        [i, struct.unpack("<I", struct.pack("<f", s))[0]]
                        for i, s in ranked(scores, allowed)[: query["k"]]
                    ]
                    checked += 1
                    if hits != query["hits"]:
                        mismatches += 1
                        if write:
                            query["hits"] = hits
    return checked, mismatches


def check_oracle(path: Path, write: bool) -> int:
    oracle = json.loads(path.read_text(encoding="utf-8"))
    checked, mismatches = recompute_oracle(oracle, write)
    verb = "rewritten" if write and mismatches else "recomputed"
    print(f"  {path.name}: {checked} queries {verb}, {mismatches} mismatches")
    if write:
        # The same compact form the crate's `mint` writes, so a re-mint and a rewrite diff cleanly.
        path.write_text(json.dumps(oracle, separators=(",", ":")), encoding="utf-8")
    return mismatches


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--write", action="store_true", help="rewrite the goldens in place")
    parser.add_argument("--check-oracle", action="store_true", help="recompute the scripted oracle; exit 1 on a mismatch")
    parser.add_argument("--write-oracle", action="store_true", help="write the scripted oracle's expectations")
    args = parser.parse_args()

    if args.check_oracle or args.write_oracle:
        mismatches = check_oracle(ORACLE_OUT, write=args.write_oracle)
        return 1 if mismatches and not args.write_oracle else 0

    total = 0
    if PIPELINE.exists():
        pipeline = json.loads(PIPELINE.read_text(encoding="utf-8"))
        changed = rescore_pipeline(pipeline)
        total += changed
        print(f"  005/hybrid.json: {changed} queries recomputed")
        if args.write and changed:
            # The generators' own bytes (`sort_keys`, two-space indent, trailing newline), so a
            # golden written here and one minted fresh hash the same.
            PIPELINE.write_text(json.dumps(pipeline, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    for name, rescore in (("search.json", rescore_search), ("mutations.json", rescore_mutations)):
        path = FIXTURES / name
        if not path.exists():
            print(f"  {name}: missing", file=sys.stderr)
            continue
        document = json.loads(path.read_text(encoding="utf-8"))
        changed = rescore(document)
        total += changed
        print(f"  {name}: {changed} expectations recomputed")
        if args.write and changed:
            path.write_text(json.dumps(document, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    if args.write:
        refresh_manifest(FIXTURES)
        refresh_manifest(PIPELINE.parent)
        return 0
    print(f"{total} expectations differ from the committed goldens" + (" (run with --write)" if total else ""))
    return 1 if total else 0


if __name__ == "__main__":
    sys.exit(main())
