#!/usr/bin/env python3
"""The Feature 024 dense-index oracle, from Python (Principle II: goldens come from
`reference/`).

`crates/xtriever-dense/tests/support/v1_oracle.json` holds three scripted sequences of
add / replace / delete / commit / reopen steps with, after every commit, five queries and the
hits the index must return — every hit's id and the IEEE-754 bits of its f32 score. The steps
were generated by the Rust test's fixed-seed LCG; the *expected hits* are what this script
recomputes, independently of the crate, from the contract's arithmetic:

- a row's stored norm is the Euclidean norm accumulated in f64 and rounded to f32 once;
- a score accumulates in f64 in component order (dot, or cosine = dot / (|q| · f64(norm_f32)),
  or −sqrt(Σ(a−b)²)) and is rounded to f32 once;
- results are ordered (score DESC, id ASC), truncated to k; an `allowed` set filters ids.

`--check` (the default) recomputes every expectation and compares it bit for bit with the
file; `--write` rewrites the file's expectations from this script. Either way the file's
steps and queries are kept, so the fixture stays reproducible from here, not from the code
under test.

    reference/.venv-012/bin/python reference/gen_024_fixtures.py [--write]
"""

from __future__ import annotations

import argparse
import json
import math
import struct
import sys
from pathlib import Path

ORACLE = Path(__file__).resolve().parent.parent / "crates/xtriever-dense/tests/support/v1_oracle.json"


def f32(x: float) -> float:
    """Round a Python float (f64) to the nearest f32, as Rust's `as f32` does."""
    return struct.unpack("<f", struct.pack("<f", x))[0]


def f32_bits(x: float) -> int:
    return struct.unpack("<I", struct.pack("<f", x))[0]


def norm_f64(v: list[float]) -> float:
    acc = 0.0
    for x in v:
        acc += x * x
    return math.sqrt(acc)


def score(metric: str, q: list[float], q_norm: float, row: list[float], row_norm_f32: float) -> float:
    if metric == "euclidean":
        acc = 0.0
        for a, b in zip(q, row):
            d = a - b
            acc += d * d
        return f32(-math.sqrt(acc))
    dot = 0.0
    for a, b in zip(q, row):
        dot += a * b
    if metric == "dot":
        return f32(dot)
    if metric == "cosine":
        return f32(dot / (q_norm * row_norm_f32))
    raise ValueError(metric)


def expected_hits(metric: str, model: dict[int, list[float]], query: dict) -> list[list[int]]:
    q = [f32(x) for x in query["vector"]]
    q_norm = norm_f64(q)
    allowed = query.get("allowed")
    scored = []
    for doc_id, row in model.items():
        if allowed is not None and doc_id not in allowed:
            continue
        s = score(metric, q, q_norm, row, f32(norm_f64(row)))
        scored.append((s, doc_id))
    # (score DESC, id ASC); -0.0 ties +0.0 exactly as float comparison does.
    scored.sort(key=lambda t: (-t[0], t[1]))
    return [[doc_id, f32_bits(s)] for s, doc_id in scored[: query["k"]]]


def replay(sequence: dict, write: bool) -> int:
    """Run the steps through a model of the committed state; check or fill the expectations."""
    metric = sequence["metric"]
    pending: dict[int, list[float] | None] = {}
    committed: dict[int, list[float]] = {}
    mismatches = 0
    for step in sequence["steps"]:
        op = step["op"]
        if op in ("add", "replace"):
            pending[step["id"]] = [f32(x) for x in step["vector"]]
        elif op == "delete":
            for doc_id in step["ids"]:
                pending[doc_id] = None
        elif op == "commit":
            for doc_id, change in pending.items():
                if change is None:
                    committed.pop(doc_id, None)
                else:
                    committed[doc_id] = change
            pending = {}
        elif op == "reopen":
            pending = {}  # uncommitted changes are gone
        elif op == "expect":
            if step["len"] != len(committed):
                if write:
                    step["len"] = len(committed)
                else:
                    mismatches += 1
            for query in step["queries"]:
                hits = expected_hits(metric, committed, query)
                if write:
                    query["hits"] = hits
                elif hits != query["hits"]:
                    mismatches += 1
        else:
            raise ValueError(op)
    return mismatches


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--write", action="store_true", help="rewrite the file's expectations from this script")
    parser.add_argument("--oracle", type=Path, default=ORACLE)
    args = parser.parse_args()
    oracle = json.loads(args.oracle.read_text(encoding="utf-8"))
    total = 0
    for sequence in oracle["sequences"]:
        mismatches = replay(sequence, args.write)
        expects = sum(1 for s in sequence["steps"] if s["op"] == "expect")
        print(f"{sequence['metric']}: {expects} commits checked, {mismatches} mismatches")
        total += mismatches
    if args.write:
        args.oracle.write_text(json.dumps(oracle, separators=(",", ":")), encoding="utf-8")
        print(f"wrote {args.oracle}")
        return 0
    print("PASS" if total == 0 else f"FAIL: {total} mismatches")
    return 0 if total == 0 else 1


if __name__ == "__main__":
    sys.exit(main())
