"""Xtriever — hybrid retrieval for RAG (BM25 → dense → fusion → re-rank), from Python.

The engine is the Rust workspace at the repository root; this package is its foreign surface
generated by uniffi (``xtriever._ffi.xtriever_ffi``, produced by the build — never committed)
plus these re-exports. Every value and every error a call returns is the engine's, bit for bit
the same as the Rust and Swift surfaces (Feature 011, ``specs/011-python-bindings``).
"""

from importlib.metadata import version as _version

from ._ffi.xtriever_ffi import (
    ChunkInfo,
    Degradation,
    DegradeReason,
    Document,
    FieldDef,
    FieldKind,
    FieldValue,
    Hit,
    HitExplain,
    IndexConfig,
    IndexHandle,
    IndexInfo,
    LoadPath,
    RerankMode,
    RerankReport,
    SearchOptions,
    SearchResponse,
    StageReport,
    XtrieverError,
)

__version__ = _version("xtriever")

__all__ = [
    "ChunkInfo",
    "Degradation",
    "DegradeReason",
    "Document",
    "FieldDef",
    "FieldKind",
    "FieldValue",
    "Hit",
    "HitExplain",
    "IndexConfig",
    "IndexHandle",
    "IndexInfo",
    "LoadPath",
    "RerankMode",
    "RerankReport",
    "SearchOptions",
    "SearchResponse",
    "StageReport",
    "XtrieverError",
    "__version__",
]
